server.port=8080

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/assetflowdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Shreeram@123

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Web Console (Disabled for MySQL)
spring.h2.console.enabled=false

# Custom JWT Properties
app.jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
app.jwt.expirationMs=86400000
